module examples/pos/exception/runtime_error

import exception

def main() = {
  def valueOrRuntimeError { p: => String / Exception[RuntimeError] }: Unit = {
    with on[RuntimeError].default { println("Runtime error encountered") }
    println(p().show)
  }

  valueOrRuntimeError { raise("This is a runtime error.") }
  valueOrRuntimeError { "No error, valid string" }
}
